# wrangler.toml
name = "yanhua-ai-citations" # The name of your worker
main = "worker.js"          # The entry point for your worker code
compatibility_date = "2023-12-01"

# This binding allows your worker to access the KV namespace.
# You must create a KV namespace in the Cloudflare dashboard and get its ID.
[[kv_namespaces]]
binding = "CITATIONS_KV" # The name of the binding in your worker code (env.CITATIONS_KV)
id = "be32ba6bf43a4643be065abca98ba906" # <-- Replace with your actual KV namespace ID

# This tells wrangler to treat the root directory as a site to be uploaded.
[site]
bucket = "./"